config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
    
 
    
  
    
  resources :docs
    
  authenticated :user do
      root "docs#index", as: "authenticated_root"
  end

   root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    
  has_many :docs
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
    before_action :find_doc, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]
    
    def index
        @docs = Doc.where(user_id: current_user)
    end
    
    def new
        @doc = current_user.docs.build
    end
    
    def create
        @doc = current_user.docs.build(doc_params)
        
        if @doc.save
            redirect_to @doc
        else
            render 'new'
        end
    end
    
    def show
        
    end
    
    def edit
    end
    
    def update
        if @doc.update(doc_params)
            redirect_to @doc
        else
            render 'edit'
        end
    end
    
    def destroy 
        @doc.destroy
        redirect_to docs_path
    end
    
    private
    
    def find_doc
        @doc = Doc.find(params[:id])
    end
    
    def doc_params
        params.require(:doc).permit(:title, :content)
    end
    
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.haml
.container
 =simple_form_for @doc do |f|
  =f.input :title
  =f.text_area :content
  %br
  =f.button :submit, class: 'btn'

app/views/docs/edit.html.haml
.container
 %h1 Edit Doc

 = render 'form'
 .my_links
  = link_to 'Cancel', doc_path

app/views/docs/index.html.haml
.container
 -unless @docs.blank?
  -@docs.each do |doc|
   %h1= link_to doc.title, doc, class: 'main'
   %p.horizontal
    %i= time_ago_in_words(doc.created_at) + ' ago'
   %br
 -else
  %h2.main Create Doc!
  %p.flow-text Start Creating Documents and Organizing your Life!

app/views/docs/new.html.haml
.container
 %h1 New Doc

 =render 'form'
 .my_links
  = link_to 'Cancel', root_path

app/views/docs/show.html.haml
.container
 %h1.center.main= @doc.title
 %p= @doc.content.html_safe
 %br
 .center.my_links
  = link_to 'All Docs', docs_path
  = link_to 'Edit', edit_doc_path
  = link_to 'Delete', doc_path, method: :delete, data: {confirm: 'Are you sure?'}

app/views/layouts/application.html.haml
!!!
%html
 %head
  %title EOffice
  = csrf_meta_tags
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <script src="https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=your_API_key"></script>
  
  = javascript_include_tag 'application'

 %body
  
  
  
  %nav
   .nav-wrapper
    = link_to 'e-OFFICE', root_path, class: 'brand-logo'
    <a href="#" data-activates="mobile-demo" class="right button-collapse"><i class="material-icons">menu</i></a>
    %ul.right.hide-on-med-and-down
     - if user_signed_in?
      %li=link_to 'Create Doc', new_doc_path
      %li=link_to 'Logout', destroy_user_session_path, method: :delete
     - else
      %li=link_to 'Login', user_session_path
      %li=link_to 'Signup', new_user_registration_path
    %ul.side-nav#mobile-demo
     - if user_signed_in?
      %li=link_to 'Create Doc', new_doc_path
      %li=link_to 'Logout', destroy_user_session_path, method: :delete
     - else
      %li=link_to 'Login', user_session_path
      %li=link_to 'Signup', new_user_registration_path
  
  
  - flash.each do |name, msg|
   = content_tag :div, msg, class: "teal lighten-4"
   
  = yield

app/views/welcome/index.html.erb
 <div id="cover" class="center">
    
    <div class="center-align info" >
      <h1 class="white-text"><span class="little_e">e</span>-Office</h1>
      <p class="white-text flow-text">Your live`s work. Organized, always.</p>
      <%= link_to 'Enter', new_user_registration_path, class: "btn waves-effect waves-light btn-large white-text darken-text-2" %>
    </div>
     
 </div>
 <br>
 <div class="container center">
     <h3>ORGANIZE</h3>
     <p>Readymade austin la croix chambray, small batch microdosing cornhole meditation neutra adaptogen 3 wolf moon gentrify normcore church-key. Occupy hell of farm-to-table, trust fund prism wolf heirloom kombucha cloud bread pop-up gluten-free etsy man braid vice offal. </p>
 </div>
 
 <br>
 <br>
 <br>
 
 <div class="action center">
    <div id="action">
     <h2>GO AHEAD!</h2>
     <%=link_to 'Join Now', new_user_registration_path, class: 'btn waves-effect waves-light btn-large white-text darken-text-2'%>
    </div>
 </div>
 
 <footer class="center">
     <p class="copy">Copyright &copy; Mladen, 2017.</p>
 </footer>